LabKey/labkey-ui-components

packages/components/.storybook/preview-head.html, packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/actions.ts, packages/components/src/components/base/LabelHelpTip.tsx, packages/components/src/components/domainproperties/AdvancedSettings.tsx, packages/components/src/components/domainproperties/ConditionalFormattingAndValidation.tsx, packages/components/src/components/domainproperties/DateTimeFieldOptions.tsx, packages/components/src/components/domainproperties/DomainForm.tsx, packages/components/src/components/domainproperties/NameAndLinkingOptions.tsx, packages/components/src/components/domainproperties/NumericFieldOptions.tsx, packages/components/src/components/domainproperties/__snapshots__/ConditionalFormattingAndValidation.spec.tsx.snap, packages/components/src/components/domainproperties/assay/AssayPropertiesInput.tsx, packages/components/src/components/domainproperties/models.ts, packages/components/src/components/lineage/Tag.tsx, packages/components/src/components/search/SearchResultCard.spec.tsx, packages/components/src/components/search/SearchResultsPanel.spec.tsx, packages/components/src/components/search/SearchResultsPanel.tsx, packages/components/src/components/search/actions.ts, packages/components/src/components/search/models.ts, packages/components/src/index.ts, packages/components/src/models.spec.ts, packages/components/src/models.ts, packages/components/src/stories/SearchResults.tsx, packages/components/webpack.config.js, packages/components/yarn.lock
- add missing "Map" imports from immutable
- fix usages of this.state() that weren't using callback version
- remove source-map setting from webpack.config.js
- remove unneeded package.json dependencies and devDependencies
=> Misc fixes and cleanup post package consolidation

packages/components/package.json, packages/components/releaseNotes/labkey/components.md
The package has already been published.
=> Bump components version to 0.1.2, add changelist notes

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/util/URLResolver.ts
Add workflow job attachment files download urls to URL resolver for search
SM PR: https://github.com/LabKey/sampleManagement/pull/129
Platform PR: https://github.com/LabKey/platform/pull/711
Issue: https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=39171
=> Secure Issue 39171: Workflow jobs are missing some search indexes

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/domainproperties/ConditionalFormattingAndValidation.tsx, packages/components/src/components/domainproperties/DomainForm.tsx, packages/components/src/components/domainproperties/DomainRow.tsx, packages/components/src/components/domainproperties/DomainRowExpandedOptions.tsx, packages/components/src/components/domainproperties/assay/AssayDesignerPanels.spec.tsx, packages/components/src/components/domainproperties/assay/AssayDesignerPanels.tsx, packages/components/src/components/domainproperties/assay/AssayPropertiesInput.tsx, packages/components/src/components/domainproperties/assay/AssayPropertiesPanel.spec.tsx, packages/components/src/components/domainproperties/assay/AssayPropertiesPanel.tsx, packages/components/src/components/domainproperties/assay/__snapshots__/AssayDesignerPanels.spec.tsx.snap, packages/components/src/components/domainproperties/assay/__snapshots__/AssayPropertiesPanel.spec.tsx.snap, packages/components/src/components/domainproperties/models.ts, packages/components/src/stories/AssayDesignerPanels.tsx, packages/components/src/stories/AssayPropertiesPanel.tsx, packages/components/src/stories/DomainForm.tsx
Associated PRs:
https://github.com/LabKey/sampleManagement/pull/142
https://github.com/LabKey/platform/pull/738
=> Omit some property types from the field designer for SM

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/actions.ts, packages/components/src/components/assay/AssayImportPanels.tsx, packages/components/src/components/assay/BatchPropertiesPanel.spec.tsx, packages/components/src/components/assay/RunDataPanel.tsx, packages/components/src/components/assay/RunPropertiesPanel.spec.tsx, packages/components/src/components/assay/__snapshots__/RunDataPanel.spec.tsx.snap, packages/components/src/components/editable/Controls.tsx, packages/components/src/components/editable/EditableGrid.tsx, packages/components/src/components/editable/EditableGridModal.tsx, packages/components/src/components/forms/BulkAddUpdateForm.tsx, packages/components/src/components/forms/BulkUpdateForm.tsx, packages/components/src/components/forms/QueryFormInputs.spec.tsx, packages/components/src/components/forms/QueryFormInputs.tsx, packages/components/src/components/forms/QueryInfoForm.tsx, packages/components/src/components/forms/input/DatePickerInput.tsx, packages/components/src/components/samples/SampleInsertPanel.tsx, packages/components/src/components/samples/models.ts, packages/components/src/index.ts, packages/components/src/stories/AssayImportPanels.tsx, packages/components/src/stories/EditableGridPanel.tsx, packages/components/src/stories/SampleInsertPanel.tsx, packages/components/src/theme/form.scss, packages/components/src/theme/index.scss, packages/components/src/util/Date.ts, packages/components/src/util/utils.ts
* Move add, bulk, edit, and delete controls to be together for SampleInsertPanel
* Add DatePickerInput
* Update QueryInfoForms to use date picker for date fields
* Add BulkAddUpdateForm
* Add support for bulk update selected grid rows for SampleInsertPanel and AssayImportPanels
* Update SampleInsertPanel to support tabbed grid and file based insert
=> Item 6364: Create Samples, Prioritized Updates

.npmrc, packages/components/.npmrc, packages/eslint-config-base/CHANGELOG.md, packages/eslint-config-base/README.md, packages/eslint-config-base/index.js, packages/eslint-config-base/package.json, packages/eslint-config-react/CHANGELOG.md, packages/eslint-config-react/README.md, packages/eslint-config-react/package.json
=> update eslint packages

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/actions.ts, packages/components/src/components/QueryGridPanel.tsx, packages/components/src/components/forms/detail/Detail.tsx, packages/components/src/components/forms/detail/DetailEditRenderer.tsx, packages/components/src/components/forms/input/DatePickerInput.tsx, packages/components/src/components/gridbar/Export.tsx, packages/components/src/components/gridbar/QueryGridBar.tsx
Issue 39461: Editing a date field in a sample does not show a date picker
Issue 39634: Export: Name being exported instead of SampleID
=> Misc sample manager 20.3 fixes

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/domainproperties/list/ListDesignerPanels.tsx, packages/components/src/components/domainproperties/list/__snapshots__/ListDesignerPanels.spec.tsx.snap, packages/components/src/components/domainproperties/list/models.spec.ts, packages/components/src/components/domainproperties/list/models.ts
Hi Cory!
Let me know if you have a different suggestion on where this should be placed, or how to go about this issue.
=> Issue39818: List designer PK fields should be shown as Required

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/base/models/model.ts, packages/components/yarn.lock
```js
// TODO why can't I use the @labkey/api enum def of containerFilter?
```
Now you can! And do!
* https://github.com/LabKey/labkey-api-js/pull/40
* https://github.com/LabKey/sampleManagement/pull/205
=> Use ContainerFilter enum

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/domainproperties/list/ListPropertiesPanel.tsx, packages/components/src/components/domainproperties/models.ts
Merge forward changes that went into the release20.3-SNAPSHOT branch, which Includes hotfix changes from version 0.31.4.
* https://github.com/LabKey/platform/pull/944
* Item 6640: Fixes for List Designer issues targeting LabKey release 20.3
=> Merge forward changes from release20.3-SNAPSHOT branch

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/error/ErrorBoundary.tsx, packages/components/src/components/error/ErrorPage.tsx, packages/components/src/index.ts, packages/components/src/testHelpers.ts, packages/components/src/theme/error.scss, packages/components/src/theme/index.scss, packages/components/src/typings/main.d.ts, packages/components/src/util/AppURLResolver.spec.ts, packages/components/yarn.lock
As a part of the work for [39867](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39867) I've created a `ErrorBoundary` HoC that allows us to display an alternative to the default "white page" when a React application crashes. After an uncaught exception happens in the React life-cycle this component will record the exception and display an `ErrorPage`.
This error page displays some useful context for when the error occurred such as the URL, logging state, reporting state, and stack trace. This stack trace is processed by [stacktrace.js](https://github.com/stacktracejs/stacktrace.js) via our `Mothership` reporting tools which binds source maps to get a more accurate context for where the error occurred.
Additionally, it displays the React "component stack" which …
=> 39867: ErrorBoundary HoC, ErrorPage to display uncaught React exceptions

packages/components/src/test/data/mixtures-getQueryPaging.json
- Each row has a unique RowId
- Solution Names are different between each sibling row
- expirationTime is the same as the index of the row (starting at 1), making it much easier to ensure that pagination information is correct
=> Fix test data for mixtures-getQueryPaging.json

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/domainproperties/dataclasses/DataClassDesigner.tsx, packages/components/src/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap, packages/components/src/components/domainproperties/dataclasses/models.ts, packages/components/src/components/domainproperties/models.spec.ts, packages/components/src/components/domainproperties/models.ts, packages/components/src/components/domainproperties/samples/SampleTypeDesigner.tsx, packages/components/src/components/domainproperties/samples/models.ts, packages/components/src/components/forms/BulkUpdateForm.tsx, packages/components/src/components/forms/QueryInfoForm.tsx, packages/components/src/stories/DataClassDesigner.tsx
- Issue 40084 - add property to exclude unique fields from bulk update modal
- Issue 39964 - overflow formatting of labels in build update modal
- Issue 40088 - add validation for reserved fields (SourceId)
=> Issues 40084, 39964, 40088: Misc. bug fixes

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/index.ts
We want to have a general way for switching between our applications.
* https://github.com/LabKey/inventory/pull/41
* Expose createApplicationUrl method
=> Item 7412: Expose createApplicationUrl utility method

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/forms/input/ColorPickerInput.tsx, packages/components/src/index.ts, packages/components/src/theme/form.scss
ELN and FreezerManagement need a color picker input.
* https://github.com/LabKey/biologics/pull/620
* Add ColorPickerInput
=> Add ColorPickerInput

packages/components/README.md
There are several steps to the merge process for releasing / publishing a new version of the @labkey/components npm package. This PR adds those steps, along with the related steps for making a release branch hotfix, to the README.
=> Update @labkey/components README with steps for merging pull requests  to master and making hotfix release branch fixes

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/auditlog/AuditDetails.tsx, packages/components/src/components/auditlog/AuditQueriesListingPage.tsx, packages/components/src/components/auditlog/actions.ts, packages/components/src/components/auditlog/models.ts, packages/components/src/components/auditlog/utils.ts, packages/components/src/components/base/models/schemas.ts, packages/components/src/components/domainproperties/models.ts, packages/components/src/components/listing/QueriesListing.tsx, packages/components/src/components/listing/SchemaListing.tsx, packages/components/src/components/listing/pages/QueriesListingPage.tsx, packages/components/src/components/listing/pages/QueryDetailPage.tsx, packages/components/src/components/listing/pages/QueryListingPage.tsx, packages/components/src/components/listing/pages/SchemaListingPage.tsx
* https://github.com/LabKey/platform/pull/1430
* Includes hotfix changes from version 0.71.3 (Issue 40795: Query metadata editor should allow editing type of field in built in table)
=> Merge forward changes from release20.7-SNAPSHOT branch

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/pagination/PageSizeMenu.tsx, packages/components/src/components/pagination/Pagination.spec.tsx, packages/components/src/components/pagination/Pagination.tsx, packages/components/src/components/pagination/PaginationInfo.tsx
We need to be rendering data attributes for tests
* https://github.com/LabKey/biologics/pull/642
* Add PaginationInfo component
=> Add PaginationInfo component

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/assay/AssayImportPanels.tsx
Need to merge recent bugfixes from release branch into master.
* n/a
* Merge 20.7-SNAPSHOT into master
=> Merge 20.7-SNAPSHOT into master

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/components/gridbar/__snapshots__/QueryGridBar.spec.tsx.snap, packages/components/src/components/gridbar/__snapshots__/QueryGridPaging.spec.tsx.snap, packages/components/src/components/pagination/PageMenu.tsx, packages/components/src/components/pagination/PageSizeMenu.tsx, packages/components/src/components/pagination/Pagination.tsx, packages/components/src/components/pagination/PaginationButton.tsx, packages/components/src/components/pagination/__snapshots__/PageSizeMenu.spec.tsx.snap
Our tests will benefit from more class names
* pending
* Add class names to PageMenu, PageSizeMenu, PaginationButton, and Pagination components
=> Add class names to pagination related components for tests

packages/components/docs/QueryModel.md, packages/components/docs/sort.md, packages/components/src/public/QueryModel/DetailPanel.tsx, packages/components/src/public/QueryModel/GridPanel.tsx, packages/components/src/public/QueryModel/withQueryModels.tsx, packages/components/src/public/sort.ts
* Fix QueryModel.md link to withQueryModels src
* Add link from public API docs to DetailPanelWithModel
* Add links from public API docs to src/public/sort.ts
=> Fix QueryModel.md link to withQueryModels and add a few more src code links from public docs

packages/components/package.json, packages/components/releaseNotes/labkey/components.md, packages/components/src/internal/components/domainproperties/ConfirmImportTypes.tsx, packages/components/src/internal/components/domainproperties/DomainForm.spec.tsx, packages/components/src/internal/components/domainproperties/DomainForm.tsx, packages/components/src/internal/components/domainproperties/DomainRow.tsx, packages/components/src/internal/components/domainproperties/DomainRowExpandedOptions.spec.tsx, packages/components/src/internal/components/domainproperties/DomainRowExpandedOptions.tsx, packages/components/src/internal/components/domainproperties/OntologyLookupOptions.spec.tsx, packages/components/src/internal/components/domainproperties/OntologyLookupOptions.tsx, packages/components/src/internal/components/domainproperties/TextFieldOptions.tsx, packages/components/src/internal/components/domainproperties/actions.spec.ts, packages/components/src/internal/components/domainproperties/actions.ts, packages/components/src/internal/components/domainproperties/assay/AssayDesignerPanels.spec.tsx, packages/components/src/internal/components/domainproperties/dataclasses/DataClassDesigner.spec.tsx, packages/components/src/internal/components/domainproperties/dataset/DatasetDesignerPanels.spec.tsx, packages/components/src/internal/components/domainproperties/dataset/DatasetDesignerPanels.tsx, packages/components/src/internal/components/domainproperties/issues/IssuesListDefDesignerPanels.spec.tsx, packages/components/src/internal/components/domainproperties/list/ListDesignerPanels.spec.tsx, packages/components/src/internal/components/domainproperties/list/ListDesignerPanels.tsx, packages/components/src/internal/components/domainproperties/list/ListPropertiesAdvancedSettings.tsx, packages/components/src/internal/components/domainproperties/list/SetKeyFieldNamePanel.tsx, packages/components/src/internal/components/domainproperties/models.spec.ts, packages/components/src/internal/components/domainproperties/models.ts, packages/components/src/internal/components/domainproperties/samples/SampleTypeDesigner.spec.tsx, packages/components/src/internal/components/domainproperties/samples/SampleTypeDesigner.tsx, packages/components/src/internal/components/domainproperties/samples/SampleTypePropertiesPanel.spec.tsx, packages/components/src/internal/components/domainproperties/samples/models.spec.ts, packages/components/src/internal/components/domainproperties/samples/models.ts
With the last set of stories to add in some features to the domain designer and fix misc issues, we decided to defer the linting of these files since it would make it more difficult for a CR of the actual story changes/fixes. This PR is now just those changes per "yarn run lint-fix" on the src/internal/components/domainproperties directory and subdirectories.
* via yarn run lint-fix
=> yarn run lint-fix on src/internal/components/domainproperties

packages/build/package-lock.json, packages/build/package.json, packages/build/releaseNotes/build.md, packages/components/package.json, packages/components/releaseNotes/components.md, packages/components/yarn.lock, packages/test/package.json, packages/test/releaseNotes/test.md, packages/test/yarn.lock, packages/themes/package.json, packages/themes/releaseNotes/themes.md, packages/themes/yarn.lock
Pulling together various dependabot PR updates into a single PR.
* https://github.com/LabKey/labkey-ui-components/pull/423
* https://github.com/LabKey/platform/pull/1816
* https://github.com/LabKey/sampleManagement/pull/442
* Package updates for @labkey/components, @labkey/build, @labkey/test, @labkey/themes
=> Dependabot package updates

packages/components/package.json, packages/components/releaseNotes/components.md, packages/components/src/internal/components/assay/AssayImportPanels.tsx, packages/components/src/internal/components/editable/EditableGrid.tsx, packages/components/src/internal/components/entities/EntityInsertPanel.tsx, packages/components/src/internal/components/forms/PageDetailHeader.tsx, packages/components/src/internal/components/forms/__snapshots__/PageDetailHeader.spec.tsx.snap, packages/components/src/theme/grid.scss
* https://github.com/LabKey/labkey-ui-components/pull/424
* https://github.com/LabKey/inventory/pull/165
* https://github.com/LabKey/sampleManagement/pull/446
* Issue 41747: Add bottom margin to EditableGrid to prevent horizontal scroll bar from covering last row
* Issue 42123: Assay import panels fix for dirty state being set on batch/run form init setValue calls
* Fix for PageDetailHeader component left padding without icon
=> Misc fixes for LKSM 21.01

packages/components/package.json, packages/components/releaseNotes/components.md, packages/components/src/internal/components/navigation/NavigationBar.tsx, packages/components/src/internal/components/navigation/__snapshots__/NavigationBar.spec.tsx.snap, packages/components/src/internal/components/notifications/ServerActivityList.tsx, packages/components/src/internal/components/notifications/ServerNotifications.tsx, packages/components/src/theme/navbar.scss
* 
*  align chevron properly with the bell icon without unread msgs
*  add line breaker between subject and detail notification
=> Issue 42342: Formatting issues with notifications drawer

packages/components/package.json, packages/components/releaseNotes/components.md, packages/components/src/internal/components/navigation/NavigationBar.tsx, packages/components/src/internal/components/navigation/ProductMenu.tsx, packages/components/src/internal/components/navigation/__snapshots__/NavigationBar.spec.tsx.snap, packages/components/src/internal/components/navigation/__snapshots__/ProductMenu.spec.tsx.snap, packages/components/src/internal/components/productnavigation/ProductNavigationHeader.spec.tsx, packages/components/src/internal/components/productnavigation/ProductNavigationHeader.tsx, packages/components/src/internal/components/productnavigation/ProductNavigationMenu.tsx, packages/components/src/theme/navbar.scss, packages/components/src/theme/product-navigation.scss
Variety of bug fixes and improvements for our app navigation and product menu.
* TBD
* [Issue 42515](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=42515): Layout issue for NavBar with medium-sized screens
* ProductMenu: prevent closing menu on non-link click
* ProductMenu: expand link clickable area
* ProductNavigationHeader: clickable text to go back
=> Product Navigation / Menu Fixes
