LabKey/labkey-ui-components

packages/querygrid/README.md
packages/querygrid/package.json
packages/querygrid/src/components/GridLoader.tsx
packages/querygrid/src/components/report-list/ReportList.spec.tsx

For some reason GridLoader was *never* using the view name from the QueryGridModel. The necessary line of code was commented out.

Fix Issue 38804

---

packages/components/package.json

We don't need to be running a build after npm install

Change prepare script to prepublishOnly

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/QueryGrid.tsx
packages/components/src/util/URL.ts

The URL listener was being called (which executed reloadQueryGridModel) before the unmount of the QueryGrid component had a chance to remove the listener. The fix here is in the listener to add a check to only call reloadQueryGridModel when the location.hash has not changed, i.e. not navigating.

QueryGrid fix to remove extra call to reloadQueryGridModel when it is being unmounted

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/base/models/model.ts

We have an issue in Biologics where if the user creates a view called `BiologicsDetails` on any item in the registry and it has a filter on it the view. If the filter removes a particular PK you are unable to view the details view for that item, It will also break the Molecule details view completely (white page error). The solution is to never apply base filters if we have a keyValue, and the view name is \~\~DETAILS\~\~.

Fix Issue 39719

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/yarn.lock

This PR doesn't do anything but bump the api-js dependency so we have the correct type signature for the selectRows failure callback.

Update @labkey/api dependency.

---

packages/components/src/components/domainproperties/list/ListPropertiesAdvancedSettings.tsx

Because the new designer lists the relevant options as, in order,
- Both metadata and data
- Data only
- Metadata only
and the old designer had, in order,
- Metadata only
- Data only
- Both metadata and data
and both sets and values were from 0 increasing to 2, the old designer and new designer radio selections weren't aligning. Talked to Binal and we decided to flip the client values for now, and put them right-side-up if we want to upon deprecating the old list designer.

Issue39813: Metadata settings in new Designer don't align with old Designer

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/actions.ts
packages/components/src/components/base/models/model.ts

- make sure baseFilters is defined before doing a concat with the rest of the filters in the model's getFilters() function

Fix for Sample Manager QueryGridModel use case that passes in undefined as baseFilters

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/list/ListPropertiesPanel.tsx
packages/components/src/components/domainproperties/models.ts

Note that this is a hotfix for the latest @labkey/components version used in platform modules in LK release20.3 (which was @labkey/components version 0.31.3):
- Issue 39846: List designer - "Name" doesn't validate immediately
- Issue 39879: Domain designer - lookup queries which only have container PK are filtered out of the select input

Item 6640: Fixes for List Designer issues targeting LabKey release 20.3

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/lineage/models.ts

The `experiment-lineage.api` changed the property "rowId" to "id". This is the corresponding change to fix the binding of `LineageNode` on the client.
* https://github.com/LabKey/platform/pull/1000

Item #6862: Switch LineageNode to bind "id" instead of "rowId"

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/user/SiteUsersGridPanel.tsx
packages/components/src/components/user/UserDetailsPanel.spec.tsx
packages/components/src/components/user/UserDetailsPanel.tsx
packages/components/src/components/user/__snapshots__/UserDetailsPanel.spec.tsx.snap
packages/components/src/stories/SiteUsersGridPanel.tsx

For LKS, we currently will hide the "Change Password" and "Reset Password" button options from the user accounts page when the server is configured to use an SSO auth configuration that is set to "auto redirect on login". We need to do the same in the SM app to conditionally hide those buttons.
* https://github.com/LabKey/platform/pull/1008
* https://github.com/LabKey/sampleManagement/pull/223
* SiteUsersGridPanel and UserDetails panel prop to hide/show 'Reset Password' button (i.e. allowResetPassword)

SiteUsersGridPanel and UserDetails panel prop to hide/show 'Reset Password' button (i.e. allowResetPassword)

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/navigation/NavigationBar.tsx
packages/components/src/components/navigation/UserMenu.tsx
packages/components/src/components/navigation/actions.ts

For the SM app, we currently redirect back to the project-start action after a user logs out. However in the trail instance case that means that the user is automatically redirected through the login loop (via the labkey.org CAS configuration on those instances). Instead we'd like to send the user to a "Sign Out Success" page after sign out of the SM app. This PR adds an optional URL for that post sign out navigation when using the UserMenu component via the NavigationBar.
* NavigationBar optional property for an alternate url to go to after sign out

NavigationBar optional property for an alternate url to go to after sign out

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/yarn.lock

Want `@labkey/components` and our apps that transitively depend on `@labkey/api` to use the latest version.
* Bumps `@labkey/api` to version `0.1.1`.

Update to latest @labkey/api

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/navigation/NavigationBar.tsx
packages/components/src/components/navigation/UserMenu.tsx
packages/components/src/components/navigation/actions.ts

For the LKSM trial logout issue 39803, changes were made in platform, cas, and other related modules to support calling the Authentication Identity Provider logout protocol when a user logs out. For the logoutApi action case, this involves a redirectUrl in the response object of that API call with the URL to call to hit the identity provider server /logout action and return accordingly. To support this, we need to handle that redirectUrl property in our signOut action which is called by the SM UserMenu "Sign Out" menu item.
* https://github.com/LabKey/platform/pull/1036
* https://github.com/LabKey/cas/pull/21
* https://github.com/LabKey/sampleManagement/pull/230
* NavigationBar optional property for an alternate url to go to after sign out
* signOut action updates to support redirectUrl …

Issue 39803: signOut action support for a redirectUrl in the response, for the CAS identity provider logout case

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/base/CreatedModified.tsx
packages/components/src/components/base/models/model.ts
packages/components/src/components/base/models/schemas.ts
packages/components/src/components/entities/__snapshots__/SingleParentEntityPanel.spec.tsx.snap
packages/components/src/components/omnibox/actions/Filter.spec.tsx
packages/components/src/components/omnibox/actions/Filter.ts
packages/components/src/components/samples/actions.ts
packages/components/src/query/api.ts
packages/components/src/url/WhereFilterType.ts
packages/components/yarn.lock

This PR incorporates updates for `@labkey/api`.
- https://github.com/LabKey/labkey-api-js/pull/51
- Support empty string URL suffix for `HAS_ANY_VALUE` filter type in Omnibox filter action.
- `Filter` updated from `splitValue` to `parseValue`.
- Typings updates.

Incorporate @labkey/api updates

---

.git-blame-ignore-revs

Don't show bulk lint update in git blame or IntelliJ annotate.
- Add .git-blame-ignore-revs file which removes these two commits from blame history (annotate)
- To add this file, git config blame.ignoreRevsFile ./.git-blame-ignore-revs

Add .git-blame-ignore-revs for bulk lint update

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/assay/AssayImportPanels.tsx
packages/components/src/components/assay/RunDataPanel.tsx
packages/components/src/components/assay/actions.spec.ts
packages/components/src/components/assay/actions.ts
packages/components/src/components/assay/models.spec.ts
packages/components/src/components/assay/models.ts
packages/components/src/components/entities/models.spec.ts
packages/components/src/components/entities/models.ts
packages/components/src/components/forms/detail/DetailEditRenderer.tsx
packages/components/src/components/forms/detail/DetailEditing.tsx
packages/components/src/components/forms/renderers.spec.tsx
packages/components/src/components/forms/renderers.tsx
packages/components/src/components/lineage/actions.ts

* https://github.com/LabKey/sampleManagement/pull/248
* Issue [40139](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40139): DetailEditing panel editing - updating time but not date does not recognize change
* Issue [39328](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39328): Assay run should use renamed file name as its Assay Id when the same data file is being imported
* Issue [40233](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40233): EntityInsertPanel columns for Sources should not include "Parents" in column name caption
* DetailEditing panel (i.e. QueryForm usage) boolean field checked state doesn't initialize correctly when formattedValue exists

Misc 20.5 issue fixes for Sample Manager

---

packages/components/docs/immer.md

This adds rationale and usage documentation around for [Immer](https://immerjs.github.io/immer/docs/introduction). I researched getting this incorporated into our TypeDoc's generated docs but there is [currently not supported](https://github.com/TypeStrong/typedoc/issues/247).
* Adds a documentation file about Immer in `packages/components/docs`.
**Note** I'd recommend reviewing this as it looks in GitHub: https://github.com/LabKey/labkey-ui-components/blob/fb_immer_docs/packages/components/docs/immer.md.

Immer documentation

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/actions.ts
packages/components/src/components/base/models/model.ts
packages/components/yarn.lock

hot fix to allow lineage query to limit to 1st generation only for sample manager 20.5
* https://github.com/LabKey/platform/pull/1118
* https://github.com/LabKey/labkey-ui-components/pull/239
* https://github.com/LabKey/sampleManagement/pull/258
* https://github.com/LabKey/labkey-api-js/pull/57
Changes
* labkey/api dependency update
* allow using separate singleFilterValue for createQueryGridModelFilteredBySample

Issue 40329: Sample Manager source samples: limit to 1st generation

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/actions.ts
packages/components/src/components/base/models/model.ts

* Includes hotfix changes from version 0.55.1
* https://github.com/LabKey/sampleManagement/pull/267
* Allow using separate singleFilterValue for createQueryGridModelFilteredBySample

Merge forward changes from release20.5-SNAPSHOT branch

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/lineage/SampleTypeLineageCounts.tsx
packages/components/src/components/lineage/actions.ts
packages/components/src/components/lineage/withLineage.tsx

This PR addresses two issues with lineage.
1. I'd originally thought that all lineage usages used the `DEFAULT_LINEAGE_DISTANCE` when none was specified, however, this isn't what was expected for `SampleTypeLineageCounts`. It expects the lineage request to not be constrained by distance/depth. This is fixed by allowing components to opt-out of defaulting to `DEFAULT_LINEAGE_DISTANCE`.
1. Lineage requests cache key include the container's id. If a container wasn't specified it was presumed to default to the current container (like all of our APIs), however, this resulted in different cache keys for the same result.  This is fixed by consistently specifying the container id for computing the cache key.
* `withLineage` allows callers to opt-out of defaulting to `DEFAULT_LINEAGE_DISTANCE`. …

Lineage: improve caching, allow non-default distance

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/dataset/DatasetColumnMappingPanel.tsx
packages/components/src/components/domainproperties/dataset/models.spec.ts
packages/components/src/components/domainproperties/dataset/models.ts

Fix for StudyScheduleTest use case which uses the text visit values instead of Sequence Num during import.
* coming soon for platform and testAutomation

Item 7207: DatasetColumnMappingPanel change to allow for numeric and text fields to be used for timepoint/visit column mapping

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/issues/IssuesListDefDesignerPanels.tsx
packages/components/src/components/domainproperties/issues/actions.ts
packages/components/src/components/domainproperties/issues/models.spec.ts
packages/components/src/components/domainproperties/issues/models.ts
packages/components/src/components/domainproperties/models.spec.ts
packages/components/src/components/domainproperties/models.ts

During the automated test conversion for the issues list def designer, a few tests failed because they were trying to save an issues list def when the fields for the def were coming from a shared domain (i.e. Shared container). This update allows for that scenario by saving just the issues list def options for the given container when the domain is shared. This fixes the RlabkeyTest, FilterTest, and IssueDomainSharingTest failures.
* https://github.com/LabKey/assayRequest/pull/27
* https://github.com/LabKey/biologics/pull/588
* https://github.com/LabKey/platform/pull/1184
* https://github.com/LabKey/testAutomation/pull/333
* Add helpers to DomainDesign model to getDomainContainer and isSharedDomain
* Allow for a shared def to be used in another container where only the top level …

Item 6646: Issues List Def support for shared domain

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/list/models.ts

Hot fix for @labkey/components targeting release20.3
- Issue 40373: List designer fails to save any changes after the list's name has been edited
https://github.com/LabKey/platform/pull/1198
- Update how key name is found and set when retrieving List options.

Item 7333 - List designer issue fix targeting release20.3

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/list/ListPropertiesAdvancedSettings.tsx

Help link under Advanced Settings takes user to List create doc instead of advanced setting section.
https://github.com/LabKey/platform/pull/1245
Update text and topic for Advance Settings help link.

Issue 40026: Change doc link from Advanced List Settings popup

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/forms/PageDetailHeader.tsx

`PageDetailHeader` requires the user if a `FieldEditTrigger` is available. This PR makes it explicitly optional to include a user when `fieldTriggerProps` not supplied.
* https://github.com/LabKey/biologics/pull/597
* Make `user` prop optional.
* Remove unused `content` prop.

PageDetailHeader no longer requires user

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/base/models/model.spec.ts
packages/components/src/components/base/models/model.ts
packages/components/src/components/navigation/NavigationBar.tsx
packages/components/src/components/navigation/__snapshots__/NavigationBar.spec.tsx.snap

As part of the freezer manager app foundations work, there were some user permissions check helper functions in the SM module that, if moved to the User model, would be easier to re-use / share.
* https://github.com/LabKey/sampleManagement/pull/282
* https://github.com/LabKey/inventory/pull/33
* Move base user permission check helpers from Sample Manager to User model
* Move related jest tests for User permission check functions to ui-components

Item 7373: Move base user permission check helpers from Sample Manager to User model

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/base/models/constants.ts
packages/components/src/components/base/models/model.ts
packages/components/src/components/domainproperties/__snapshots__/LookupFieldOptions.spec.tsx.snap
packages/components/src/components/forms/PageDetailHeader.tsx
packages/components/src/components/forms/actions.ts
packages/components/src/components/forms/input/UserSelectInput.tsx
packages/components/src/components/forms/model.ts
packages/components/src/components/user/actions.ts
packages/components/src/global.ts
packages/components/src/index.ts
packages/components/src/typings/global.d.ts
packages/components/src/util/utils.spec.ts
packages/components/yarn.lock

With https://github.com/LabKey/labkey-api-js/pull/65 `@labkey/api` now exposes additional interfaces and wraps the `user-getUserWithPermissions.api` endpoint. This PR switches `@labkey/components` to use those interfaces instead of declaring it's own and makes use of the new endpoint.
* https://github.com/LabKey/labkey-api-js/pull/65
* https://github.com/LabKey/platform/pull/1282
* Remove `IUser` interface in favor of direct use of `@labkey/api` `User` and `UserWithPermissions` interfaces.
* `PermissionsType` enum migrated to `@labkey/api`.

Use User, Security.getUserWithPermissions from @labkey/api

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/omnibox/OmniBox.tsx

This PR fixes [Issue 39206](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39206) by removing filters against the selected column prior to making the `Query.selectDistinctRows` call to fetch results for that column. As a result, when a user activates a previously defined OmniBox filter they will get the same behavior as composing a new one.
* Strip filters against the selected column from the `Query.selectDistinctRows` options in `OmniBox`.

39206: Remove filters against selected column in OmniBox

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/index.ts

The addModel method from withQueryModels expects the QueryConfig type, so this exposes that type
* https://github.com/LabKey/labkey-ui-components/pull/273
* Add QueryConfig type to index.ts

Fb fm freezer delete

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/QueryModel.spec.ts
packages/components/src/QueryModel/QueryModel.ts

The QueryGridModel object has a getRow helper which allows access to a row of data in the model by key, or access to the first row if no key is provided. This helper is useful for the "single model row details" type of usage. This PR adds a similar getRow helper to the QueryModel object
* https://github.com/LabKey/inventory/pull/38
* add getRow() helper for getting first row of QueryModel.rows object

Item 7417: QueryModel - add getRow() helper for getting first row of QueryModel.rows object

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/omnibox/actions/Search.ts
packages/components/src/components/omnibox/actions/Sort.ts
packages/components/src/components/omnibox/actions/View.ts

The Omnibox doesn't show sorts when URLPrefix is used, Biologics uses the URL prefix often, specifically on the assay pages. Not seeing or being able to clear sorts from the URL is a usability problem.
* n/a
* Don't toLowerCase compare the paramKey in Sort.matchParam

Fix Issue 39947 - ﻿Omnibox doesn't show sorts when URLPrefix is used 

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/QueryModel.ts
packages/components/src/QueryModel/utils.spec.ts
packages/components/src/QueryModel/utils.ts
packages/components/src/components/base/models/QueryInfo.spec.ts
packages/components/src/components/base/models/QueryInfo.ts
packages/components/src/index.ts

For the Freezer Creation story in the Freezer Manager app, there is a "domain designer" like page for the freezer creation / update form UI. Instead of reinvent the panel collapse/expand, status icon, error display, etc., this BasePropertiesPanel can be reused for the panels of this new freezer designer.
* https://github.com/LabKey/inventory/pull/39
* Add BasePropertiesPanel to the index.ts for use in apps
* QueryInfo - add getColumnFieldKeys helper method to get fieldKeys for select columns
* QueryModel - add parameter to getRow method to allow for a flattened key/value pair response object

Item 7417: BasePropertiesPanel - add to index.ts for use in Freezer Manager app

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/QueryModelLoader.ts
packages/components/src/components/ExpandableContainer.tsx

This PR includes 2 small changes to support location list display for FM. In order to use ExpandableContainer for FM location listing, a onclick hook is needed to wire up action for expand/collapsing a row. Additionally, QueryModelLoader should use parameters instead of queryParameters. 
* https://github.com/LabKey/inventory/pull/40
* change QueryModelLoader queryParameters to parameters
* add onClick prop for ExpandableContainer

Item 7445: Freezers on the Dashboard

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/validation/Filters.tsx

Decode the correct part of filter type string.
https://github.com/LabKey/platform/pull/1339

Issue 40555: QC state conditional formats work but are not viewable/editable in Query Metadata editor

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/permissions/EffectiveRolesList.spec.tsx
packages/components/src/components/permissions/EffectiveRolesList.tsx
packages/components/src/components/permissions/PermissionAssignments.tsx
packages/components/src/components/permissions/__snapshots__/EffectiveRolesList.spec.tsx.snap
packages/components/src/components/user/UserDetailsPanel.tsx
packages/components/src/test/data/security-getPolicyRoot.json

Issue [39263](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=39263) - in the Sample Manager app, the permissions page allows for a user to click on a role assignment to view details about the selected user. This user details shows a listing of the "Effective Roles" for that user in the current container. To date, that listing is only the roles assigned to that user in the current container (i.e. in the Sample Manager project). It does not include the roles assigned to that user at the root level (i.e. Application Admin).
* https://github.com/LabKey/sampleManagement/pull/307
* PermissionAssignments.tsx update to include display of root assignments in Effective Roles listing

Issue 39263 - PermissionAssignments.tsx update to include display of root assignments in Effective Roles listing

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/QueryGridPanel.tsx
packages/components/src/components/entities/__snapshots__/SingleParentEntityPanel.spec.tsx.snap

This PR adds a new boolean prop to `QueryGridPanel` (QGP) called `initModelOnMount` which allows the user to elect to prevent the QGP from calling `gridInit()` when it mounts. This allows the `QueryGridModel` (QGM) to be initialized by components that initialize the model from `componentDidMount()`.
During investigation of switching components to use `componentDidMount()` in <Biologics PR> a subtle behavior became apparent when calling `gridInit()` from multiple components on the same model. In short, the highest level component that relies on the QGM's state should be responsible for calling `gridInit(model, true, this)`. Here is an example:
1. Parent component initializes a QGM and calls `gridInit(model, true, this)` via `componentDidMount()` and passes model to child QGP in `render()`. …

QueryGridPanel "initModelOnMount" prop

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/forms/input/LookupSelectInput.tsx

When we don't use an `isLoading` property, we will almost certainly make multiple calls to load the options for a LookupSelectInput (primarily used in the workflow components in SampleManager).
* https://github.com/LabKey/sampleManagement/pull/316
* Add isLoading property on LookupSelectInput

Protect against redundant calls to get lookup options

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/domainproperties/DomainRow.tsx
packages/components/src/components/domainproperties/__snapshots__/ConditionalFormattingAndValidation.spec.tsx.snap
packages/components/src/components/domainproperties/__snapshots__/DomainRow.spec.tsx.snap
packages/components/src/components/domainproperties/__snapshots__/DomainRowExpandedOptions.spec.tsx.snap
packages/components/src/components/domainproperties/__snapshots__/LookupFieldOptions.spec.tsx.snap
packages/components/src/components/domainproperties/__snapshots__/NameAndLinkingOptions.spec.tsx.snap
packages/components/src/components/domainproperties/assay/__snapshots__/AssayDesignerPanels.spec.tsx.snap
packages/components/src/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap
packages/components/src/components/domainproperties/models.ts
packages/components/src/components/domainproperties/samples/__snapshots__/SampleTypeDesigner.spec.tsx.snap

This PR allows the editing of datatype for domain fields of both user defined queries and built in tables while keeping the name property locked. Name of an alias field is still editable.
* https://github.com/LabKey/platform/pull/1364
* introduced a new boolean: lockExistingField on DomainField model to lock Name and hide delete Icon for the fields in built in table and user defined queries.

Issue 40795: Query metadata editor should allow editing type of field in built in table

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/index.ts
packages/components/src/renderers/StorageStatusRenderer.tsx
packages/components/src/util/URLResolver.ts

We are adding columns in our samples grids for SampleManager that will show the storage status for each sample and link to the appropriate location in the FreezerManager application when a sample is in storage.  Thus our URLResolvers need to be able to handle linking outside the current application
* https://github.com/LabKey/platform/pull/1388
* https://github.com/LabKey/sampleManagement/pull/325
* https://github.com/LabKey/inventory/pull/55
* https://github.com/LabKey/biologics/pull/632
* Update URLResolvers to handle URLs that may go to a separate application
* Add StorageStatusRenderer for showing the storage status of a sample

Item 7493: Support for adding storage status columns in sample grids and resolving URLs to other applications 

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/base/ColorIcon.spec.tsx
packages/components/src/components/base/ColorIcon.tsx
packages/components/src/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap
packages/components/src/components/domainproperties/dataclasses/__snapshots__/DataClassPropertiesPanel.spec.tsx.snap
packages/components/src/components/domainproperties/entities/EntityDetailsForm.tsx
packages/components/src/components/domainproperties/entities/__snapshots__/EntityDetailsForm.spec.tsx.snap
packages/components/src/components/domainproperties/samples/SampleTypeDesigner.spec.tsx
packages/components/src/components/domainproperties/samples/SampleTypeDesigner.tsx
packages/components/src/components/domainproperties/samples/SampleTypePropertiesPanel.spec.tsx
packages/components/src/components/domainproperties/samples/SampleTypePropertiesPanel.tsx
packages/components/src/components/domainproperties/samples/__snapshots__/SampleTypeDesigner.spec.tsx.snap
packages/components/src/components/domainproperties/samples/__snapshots__/SampleTypePropertiesPanel.spec.tsx.snap
packages/components/src/components/domainproperties/samples/models.spec.ts
packages/components/src/components/domainproperties/samples/models.ts
packages/components/src/components/forms/detail/DetailEditRenderer.tsx
packages/components/src/components/forms/input/ColorPickerInput.spec.tsx
packages/components/src/components/forms/input/ColorPickerInput.tsx
packages/components/src/components/forms/input/__snapshots__/ColorPickerInput.spec.tsx.snap
packages/components/src/index.ts
packages/components/src/renderers/LabelColorRenderer.spec.tsx
packages/components/src/renderers/LabelColorRenderer.tsx
packages/components/src/renderers/__snapshots__/LabelColorRenderer.spec.tsx.snap
packages/components/src/stories/ColorIcon.tsx
packages/components/src/stories/ColorPickerInput.tsx
packages/components/src/stories/SampleTypeDesigner.tsx
packages/components/src/test/data/property-getDomain-sampleType.json
packages/components/src/theme/form.scss

There are expectations that there will be several sample types used in the Sample Manager and Freezer Manager apps. To distinguish them quickly in various parts of the UI, we are adding a "Label Color" property to the Sample Type so that it can be tagged with a color to be used in things like the Freezer box display and grid.
This PR adds or updates some shared components related to showing a color icon in various places. The existing ColorPickerInput, used by ELN, was updated for use with the SampleTypeDesigner and a ColorIcon component was added for display purposes.
* https://github.com/LabKey/platform/pull/1389
* https://github.com/LabKey/sampleManagement/pull/324
* https://github.com/LabKey/inventory/pull/54
* ColorPickerInput updates to support showing color chip within dropdown …

Item 7563: SampleTypeDesigner update to add "Label Color" property to Sample Manager

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/auditlog/AuditDetails.tsx

We want to show the location event on Sample's timeline when a sample is added to a storage location in freezer. A gridColumnRenderer is added to AuditDetaiils so that box can link to its freezermanager page from sample manager. When we work on the future story to supporting routing between LKSM and LKFM in a more general way, we can then re-consider the approach. 
* https://github.com/LabKey/labkey-ui-components/pull/300
* https://github.com/LabKey/inventory/pull/58
* https://github.com/LabKey/sampleManagement/pull/327
* Support custom gridColumnRenderer for AuditDetails

Item 7565: Box display, Putting Samples in a Box

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/app/models.ts

Our tests currently require that "LABKEY.user.id" be defined in the `jest` global configuration to avoid an undefined reference when setting the `AppModel.initialUserId`. This PR makes it so the `User` model is used to source the `initialUserId` which will now be fulfilled by the `defaultUser` properties for any property not defined via `getServerContext().user`.
* Use default `User` model properties to populate `AppModel.initialUserId`.

getServerContext().user may not be defined

---

README.md

Shows TeamCity status and gives an easy way for people to locate the test results for this repository.
* Add status icon to README:

Add TeamCity status icon

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/ChartMenu.tsx
packages/components/src/QueryModel/DetailPanel.tsx
packages/components/src/QueryModel/GridPanel.spec.tsx
packages/components/src/QueryModel/GridPanel.tsx
packages/components/src/QueryModel/QueryModel.ts
packages/components/src/QueryModel/QueryModelLoader.ts
packages/components/src/QueryModel/testUtils.ts
packages/components/src/QueryModel/utils.ts
packages/components/src/QueryModel/withQueryModels.spec.tsx
packages/components/src/QueryModel/withQueryModels.tsx
packages/components/src/components/base/models/model.ts
packages/components/src/components/chart/ChartMenuItem.tsx
packages/components/src/components/chart/ChartModal.tsx
packages/components/src/components/lineage/node/LineageDetail.tsx
packages/components/src/components/omnibox/actions/Filter.ts
packages/components/src/components/omnibox/actions/Search.ts
packages/components/src/components/omnibox/actions/Sort.ts
packages/components/src/components/omnibox/actions/View.ts
packages/components/src/components/pagination/Pagination.tsx
packages/components/src/index.ts
packages/components/src/models.ts
packages/components/src/stories/QueryModel.tsx
packages/components/yarn.lock

We need QueryModel and withQueryModels to support URL binding so we can begin to replace existing usages of QueryGridModel in Biologics and Sample Manager that persist some model state to the URL.
* n/a at the moment but will be needed in Biologics and Sample Manager
* Implement URL Binding for QueryModel/withQueryModels
* For this feature to work your usage of withQueryModels must be a child of a configured React Router (see
packages/components/src/stories/QueryModel.tsx for an example)
* QueryModel: charts has been changed from IDataViewInfo to DataViewInfo
* QueryModelLoader has been updated to support this
* Fixed an issue in DefaultQueryModelLoader where loadCharts was returning unsupported charts.
* QueryModel: Added fields
* bindURL
* selectedReportId
* QueryModel: Added …

QueryModel URL Binding

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/QueryModelLoader.ts
packages/components/src/actions.ts
packages/components/src/components/GridLoader.tsx
packages/components/src/components/auditlog/AuditQueriesListingPage.tsx
packages/components/src/components/editable/EditableGridLoaderFromSelection.tsx
packages/components/src/components/entities/actions.ts
packages/components/src/components/forms/BulkUpdateForm.tsx
packages/components/src/components/user/SiteUsersGridPanel.tsx
packages/components/src/index.ts

Freezer Management functionality uses parameterized queries for a number of its grids, so we need to add support for selecting and de-selecting items in such grids that are backed by parameterized queries.  We also need to be able to retrieve the records for all selected items, not just those on the current page in order to do certain operations, so we expose an action for doing that.
* https://github.com/LabKey/inventory/pull/59
* Add support for parameterized queries when getting and setting selections on a grid
* Export getSelectedData method

Item 7513: Add support for parameterized queries and retrieving selected data with selection operations 

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/auditlog/AuditDetails.tsx
packages/components/src/components/auditlog/AuditQueriesListingPage.tsx
packages/components/src/components/auditlog/actions.ts
packages/components/src/components/auditlog/models.ts
packages/components/src/components/auditlog/utils.ts
packages/components/src/components/base/models/schemas.ts
packages/components/src/components/listing/QueriesListing.tsx
packages/components/src/components/listing/SchemaListing.tsx
packages/components/src/components/listing/pages/QueriesListingPage.tsx
packages/components/src/components/listing/pages/QueryDetailPage.tsx
packages/components/src/components/listing/pages/QueryListingPage.tsx
packages/components/src/components/listing/pages/SchemaListingPage.tsx

Misc linting and cleanup of the audit log and schema browser related components that were factored out of the Sample Manager app so that they could be shared between that app and the Freezer Manager app, and maybe Biologics in the future.
Author: @labkey-nicka 
* https://github.com/LabKey/inventory/pull/56
* https://github.com/LabKey/sampleManagement/pull/326

Audit and schema browser component linting and misc cleanup after move from Sample Manager app

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/utils.ts
packages/components/src/index.ts

Need a QueryModel aware method for calculating the columns needed for the assay run details page which I am currently refactoring to use QueryModel.
* https://github.com/LabKey/biologics/pull/642
* Add runDetailsColumnsForQueryModel - convenience method for calculating the columns needed for an assay run details page, adapted from getRunDetailsQueryColumns.

Add runDetailsColumnsForQueryModel

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/PreviewGrid.spec.tsx
packages/components/src/components/QueryGridPanel.spec.tsx
packages/components/src/components/base/models/QueryInfo.ts
packages/components/src/components/lineage/grid/LineageGrid.spec.tsx
packages/components/src/index.ts
packages/components/src/test/data/sampleSetSearchResult.json
packages/components/src/testHelpers.ts
packages/components/src/util/AppURLResolver.spec.ts
packages/components/src/util/URLResolver.spec.ts
packages/components/src/util/URLResolver.ts
packages/components/src/util/URLService.spec.ts
packages/components/src/util/URLService.ts
packages/components/src/util/messaging.tsx

Different applications route URLs differently, so we have refactored the URLMapper class to require that applications register their own mappers. This allows us to move application-specific mappers into their respective applications.
* https://github.com/LabKey/inventory/pull/60
* https://github.com/LabKey/sampleManagement/pull/331
* https://github.com/LabKey/biologics/pull/641
* Add method for applications to register their URL Mappers so different applications can choose to route Server URLs differently.
* Add a productId property to ActionMapper so it can be used to construct a URL to a separate application.
* Eliminate deprecated `showMaterialSource` link mapping

Item 7622: Updates to URL routing for better between-application routing

---

packages/components/README.md
packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/testUtils.ts
packages/components/src/QueryModel/withQueryModels.tsx
packages/components/src/components/base/ColorIcon.tsx
packages/components/src/components/base/Grid.tsx
packages/components/src/index.ts
packages/components/src/stories/ColorIcon.tsx
packages/components/src/theme/form.scss

Freezer box viewer uses Grid for rendering and needs to be in sync with QueryModel's selection state. A few changes are made to allow more flexible styling of grid, and also to allow easy selection updates for QueryModel.  
* https://github.com/LabKey/labkey-ui-components/pull/309
* https://github.com/LabKey/sampleManagement/pull/333
* https://github.com/LabKey/inventory/pull/61
* Add headerCls prop to GridColumn
* Add useSmall prop to ColorIcon to show small sized icon
* Add setSelections and replaceSelections to QueryModel Actions
* Export cancelEvent method

Item 7611 - freezer box display 

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/GridPanel.tsx
packages/components/src/QueryModel/QueryModel.ts
packages/components/src/components/base/Section.tsx
packages/components/src/components/base/__snapshots__/Section.spec.tsx.snap
packages/components/src/components/chart/BaseBarChart.tsx
packages/components/src/components/chart/utils.spec.ts
packages/components/src/components/chart/utils.ts
packages/components/src/components/user/UserProvider.tsx
packages/components/src/components/user/actions.spec.ts
packages/components/src/index.ts
packages/components/src/renderers/StorageStatusRenderer.tsx
packages/components/src/stories/Section.tsx
packages/components/src/test/data/AssayRunCounts-getQueryRows.json
packages/components/src/theme/charts.scss
packages/components/src/theme/section.scss

We are adding bar graphs to the Freezer Management dashboard and adjusting some styling for both FM and SM dashboards to be more consistent.  We are making more use of the `Section` component and need it to be more configurable.  And we've move a general `UserProvider` and `BarChartBase` from sampleManagement to here.
* https://github.com/LabKey/platform/pull/1455
* https://github.com/LabKey/sampleManagement/pull/338
* https://github.com/LabKey/inventory/pull/63
* Section component is now a PureComponent with css classes and more customizable styles
* Add UserProvider for getting a user and user properties onto a page
* Surface emptyText and showHeader properties of Grid through GridPanel
* Update to StorageStatusRenderer for different text representing "not in storage"
* Move …

Item 7586: Updates to support common dashboard panels for applications

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/chart/BaseBarChart.tsx
packages/components/src/components/chart/utils.spec.ts
packages/components/src/components/chart/utils.ts
packages/components/src/test/data/AssayRunCounts-getQueryRows.json

With sample types in LKS having a LabelColor property, we want to start using that in more places in the SM and FM apps. Each of those apps have a dashboard bar chart section. In order to make use of those sample type labelcolors in the bar chart we need some property updates to the BaseBarChart and processChartData() to allow usages to identify properties of the chart data which can be used for the per-bar fill color designation.
* https://github.com/LabKey/sampleManagement/pull/339
* https://github.com/LabKey/inventory/pull/64
* BaseBarChart updates to support per-bar fill color designation and usage of that in the bar chart config scale object
* processChartData() updates to include a map of barFillColors based on a colorPath variable from the response data

BaseBarChart and processChartData() updates to support per-bar fill color designations

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/forms/BulkUpdateForm.tsx

In Biologics samples, if you go from the grid to bulk edit, then select edit in grid, sample ids were not being shown.  This passes through the readonly columns to the editable grid through the bulk edit UI.
https://github.com/LabKey/biologics/pull/648
- Add readonly columns to BulkUpdateForm and add them to the list of columns passed to EditableGrid

Issue 40965: Navigating to sample edit grid via bulk-edit grid does not show sampleIds in the edit grid

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/QueryModel/ChartMenu.tsx
packages/components/src/QueryModel/DetailPanel.tsx
packages/components/src/QueryModel/EditableDetailPanel.tsx
packages/components/src/QueryModel/GridPanel.spec.tsx
packages/components/src/QueryModel/GridPanel.tsx
packages/components/src/QueryModel/QueryModel.ts
packages/components/src/actions.ts
packages/components/src/components/base/CreatedModified.tsx
packages/components/src/components/editable/EditableGridLoaderFromSelection.tsx
packages/components/src/components/forms/BulkUpdateForm.tsx
packages/components/src/components/forms/detail/DetailEditing.tsx
packages/components/src/components/forms/detail/utils.ts
packages/components/src/components/menus/SelectionMenuItem.tsx
packages/components/src/global.ts
packages/components/src/index.ts
packages/components/src/renderers.tsx
packages/components/src/stories/QueryModel.tsx

I'm in the process of refactoring some of SampleManager to use the QueryModel API and I needed to make some components unaware of either model, and I needed an eitable details panel.
* https://github.com/LabKey/sampleManagement/pull/342
* Refactor several components/classes to not depend on QueryGridModel
* This allows them to more easily be used by QueryModel and QueryGridModel based components while we transition
away from QueryGridModel
* Affected Components: SelectionMenuItem, BulkUpdateModel
* Affected Classes: EditableGridLoaderFromSelection
* Add EditableDetailPanel, the QueryModel version of DetailEditing
* DetailPanel: change queryColumns prop from List<QueryColumn> to QueryColumn[]
* We are moving away from Immutable and want to limit how much of it is exposed in our API
* …

EditableQueryGridPanel, reduce QueryGridModel usages

---

packages/components/src/components/domainproperties/BooleanFieldOptions.spec.tsx
packages/components/src/components/domainproperties/ConditionalFormattingAndValidation.spec.tsx
packages/components/src/components/domainproperties/DateTimeFieldOptions.spec.tsx
packages/components/src/components/domainproperties/LookupFieldOptions.spec.tsx
packages/components/src/components/domainproperties/NameAndLinkingOptions.spec.tsx
packages/components/src/components/domainproperties/NumericFieldOptions.spec.tsx
packages/components/src/components/domainproperties/TextFieldOptions.spec.tsx
packages/components/src/components/domainproperties/validation/ConditionalFormatOptions.spec.tsx
packages/components/src/components/domainproperties/validation/Filters.spec.tsx
packages/components/src/components/domainproperties/validation/RangeValidationOptions.spec.tsx
packages/components/src/components/domainproperties/validation/RegexValidationOptions.spec.tsx
packages/components/src/components/navigation/ProductMenuSection.spec.tsx

Removes redundant usages of the `enzyme-to-json` package as it is already configured via `package.json` when setting the `snapshotSerializers`.
```json
"snapshotSerializers": [
"enzyme-to-json/serializer"
],
```
**Note!** Since this PR only touches test files I do not plan on bumping the package version.
* Remove explicit calls to `enzyme-to-json` in favor of implicit configuration declaration.

Remove explicit usages of enzyme-to-json

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/assay/AssayImportPanels.tsx

With Biologics recently updated to use AssayImportPanels Issue 38711 was re-introduced. I have updated AssayImportPanels to inject the assayRequest id if it is on the URL.
* https://github.com/LabKey/biologics/pull/658
* Inject the assayRequest ID into the runProperties data if it is on the URL

20.7 - Fix 38711

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/auditlog/TimelineView.tsx
packages/components/src/components/auditlog/__snapshots__/TimelineView.spec.tsx.snap
packages/components/src/components/auditlog/models.ts
packages/components/src/query/api.ts
packages/components/src/test/data/constants.ts
packages/components/src/theme/timeline.scss
packages/components/yarn.lock

When checking items in and out of the freezer, we want to allow users to optionally provide comments on the action. These comments are naturally associated with the audit event, not with the sample or the inventory item, so we provide a parameter in the request for attaching the user comments that can then be passed through to the methods for creating the audit events. They are to be surfaced with the sample timeline and inventory location history views within the applications.
* https://github.com/LabKey/sampleManagement/pull/351
* https://github.com/LabKey/platform/pull/1512
* https://github.com/LabKey/labkey-api-js/pull/73
* https://github.com/LabKey/inventory/pull/75
* Add optional display of comments from event metadata with timeline events
* Add optional `auditUserComment` when …

Item 7514: Allow users to attach comments for the audit log when inserting, updating, or deleting rows

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/base/LoadingSpinner.tsx
packages/components/src/components/listing/pages/QueryDetailPage.tsx
packages/components/src/components/listing/pages/QueryListingPage.tsx

The implementation for the `/q` route pages in Biologics were recently updated by @labkey-alan to use `QueryModel`. This PR migrates these implementations into their corollary in `@labkey/components`.
* https://github.com/LabKey/biologics/pull/671
* https://github.com/LabKey/sampleManagement/pull/359
* https://github.com/LabKey/inventory/pull/85
* `QueryListingPage` and `QueryDetailPage` refactored to use `QueryModel` approach.

Use QueryModel in query pages

---

packages/components/releaseNotes/labkey/test.md
packages/test/package.json
packages/test/src/index.ts
packages/test/src/integrationUtils.ts
packages/test/src/test/example.ispec.ts
packages/test/yarn.lock

This PR adds several features to the `@labkey/test` integration test utilities. These are exposed on the `IntegrationTestServer` interface:
* `addUserToRole` - Add a user (by their email address) to a permission's role in a the test container. This allows for testing of users with different permissions in the test container.
* `createRequestContext `- Creates a RequestContext that can be used for subsequent server requests (e.g. get, post). This will initialize the CSRF token to ensure that the server requests authenticate as expected.
* `createTestContainer` - Creates a new Container on the server within the test Project. This allows for testing across multiple containers or creating a separate container for a test suite.
* `createUser` - Create a new user account on the server with the …

@labkey/test: Support multiple containers and users

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/__snapshots__/QueryGridPanel.spec.tsx.snap
packages/components/src/components/entities/EntityDeleteConfirmModal.tsx
packages/components/src/components/entities/EntityDeleteConfirmModalDisplay.tsx
packages/components/src/components/entities/EntityDeleteModal.tsx
packages/components/src/components/forms/FieldEditorOverlay.tsx
packages/components/src/components/forms/detail/__snapshots__/Detail.spec.tsx.snap
packages/components/src/components/forms/detail/__snapshots__/DetailEditing.spec.tsx.snap
packages/components/src/renderers/DefaultRenderer.tsx
packages/components/src/theme/detail.scss

When deleting samples in sample manager with freezer manager enabled, the deletion causes a cascade of deletions of items from the inventory tables.  We want to be able to customize the message to users so that it says "permanently deleted and removed from storage" vs. just "permanently deleted", so we allow the verb to be customized.
I've also included here a seemingly small styling change for detail display that will preserve line breaks in multi-line detail fields.  I may regret trying to do these two unrelated changes together.  We'll see how unhappy the tests are.
* https://github.com/LabKey/platform/pull/1558
* https://github.com/LabKey/inventory/pull/88
* https://github.com/LabKey/sampleManagement/pull/363
* Add optional verb property to EntityDeleteConfirmModal
* Add styling to …

Issues 41327 and 37931: Add optional verb property to delete confirmation and update formatting for DetailDisplay

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/index.ts
packages/components/src/util/utils.spec.ts
packages/components/src/util/utils.ts

Unique names are not enforced for samples when they belong to different sample types, or data from different data classes. When generating SelectInput options, we want to append sample type or source type to entries with duplicate names so user know which item they are selecting.
* https://github.com/LabKey/inventory/pull/92
* https://github.com/LabKey/sampleManagement/pull/365
* Add getDisambiguatedSelectInputOptions util

Issue 41278: repeated sample ids in parent dropdown

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/components/files/FileTree.tsx
packages/components/src/index.ts

Module root name rather than 'root' is desired as the label of a root node within FileTree
* https://github.com/LabKey/moduleEditor/pull/12
* https://github.com/LabKey/platform/pull/1576
* Add optional prop for root node

7857: Apply moduleEditor feedback

---

packages/components/releaseNotes/labkey/test.md
packages/test/package.json
packages/test/src/index.ts
packages/test/src/integrationUtils.ts

Expose additional test user context so that tests don't have to re-query for user information.
* https://github.com/LabKey/biologics/pull/685
* Define and export a `TestUser` interface with richer user context. This is now what is returned by `IntegrationTestServer.createUser()`.

@labkey/test: Expose additional test user context

---

README.md
packages/components/releaseNotes/labkey/test.md
packages/test/package.json
packages/test/src/integrationUtils.ts

Expose the default request context so it is available on `IntegrationTestServer`.
* Add `requestContext` to the `IntegrationTestServer` interface and initialize to `server.defaultContext`.
* (Unrelated) Add link to `@labkey/themes` in top-level Readme.

@labkey/test: Expose default request context

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/domainproperties/ConditionalFormattingAndValidation.tsx
packages/components/src/internal/components/domainproperties/__snapshots__/DomainRow.spec.tsx.snap
packages/components/src/internal/components/domainproperties/__snapshots__/DomainRowExpandedOptions.spec.tsx.snap
packages/components/src/internal/components/domainproperties/dataset/DatasetPropertiesAdvancedSettings.tsx
packages/components/src/internal/components/domainproperties/dataset/DatasetPropertiesPanel.tsx
packages/components/src/internal/components/domainproperties/validation/ConditionalFormatOptions.tsx
packages/components/src/internal/components/domainproperties/validation/ValidatorModal.tsx
packages/components/src/internal/components/domainproperties/validation/__snapshots__/ConditionalFormatOptions.spec.tsx.snap

Issue [41431](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41431): Confusing text in Conditional Formats UI
* https://github.com/LabKey/platform/pull/1601
* https://github.com/LabKey/testAutomation/pull/483
* Make add and remove buttons on conditional format and validator dialogs consistent
* Fix for expanded field row section header for when conditional format is shown but neither validator

Issue 41431: Misc test fixes on domain designer conditional format dialog and buttons

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/app/scss/variables.scss

Caught and troubleshot by Cory, some of the Bootstrap variable overrides are not coming through.  Need to import bootstrap variables after BS overrides [per sass instructions](https://github.com/twbs/bootstrap-sass#sass-1)
- Move bootstrap variables import to bottom of variables.scss.  Define $grid-gutter-width same as default BS value as it is used in an override before import.

Move bootstrap import to bottom per BS instructions

---

.gitignore
packages/components/package-scripts.js
packages/components/tsconfig.json
packages/components/webpack.config.js

We are introducing the use of webpack aliases for better hot-reloading of changes from this package and other premium packages within module applications.  When these aliases are in place, the disappearance of the `dist` directory during the build process causes a recompile of the application that fails (because the dist directory is missing) and then another one that succeeds when the directory appears again.  Using a staging directory prevents the first failed build of the application.
See also: [Sharing Premium Components](https://docs.google.com/document/d/1yPNqONxO23BFPNdyZbLXMlYwinDBTgzbimKSyhuvOUI/edit#)
* https://github.com/LabKey/inventory/pull/104
* https://github.com/LabKey/platform/pull/1615
* https://github.com/LabKey/sampleManagement/pull/378
* …

Introduce use of staging directory when building for better hot reloading using webpack aliases

---

packages/components/package.json
packages/components/src/internal/components/report-list/__snapshots__/ReportList.spec.tsx.snap
packages/components/yarn.lock

Updates the `test` target to only run tests. TeamCity has been configured by @labkey-tchad to run the compilation of storybook and the docs as separate build steps which call their associated target (i.e. `build-storybook` and `build:docs`).
Additionally, I've regenerated the `yarn.lock` using the latest version of yarn (`v1.22.10`) to bump the transitive dependencies in the associated packages. This alleviates the issue that storybook is running into when attempting to be compiled in our TC environments. **Note**, one of these updates caused a single test snapshot to have to be updated due to the change in how anonymous functions are labeled (uhh, cool?).
Failure being thrown by storybook build:
* Update `test` target to only run jest unit tests (no longer additionally builds storybook …

Update "test" target, yarn.lock for storybook build

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/index.ts
packages/components/src/internal/actions.ts
packages/components/src/internal/components/entities/EntityInsertPanel.tsx
packages/components/src/internal/query/api.ts
packages/components/src/public/QueryModel/QueryModelLoader.ts
packages/components/src/public/QueryModel/withQueryModels.tsx
packages/components/src/test/MockQueryModelLoader.ts
packages/components/src/theme/notification.scss

Within LKSM, we want to enable users to work with the samples and sources that have just been imported, either via a file import or import within a grid.  Currently, this is possible when importing from a grid because the records created from using the `insertRows` operation are returned in the api response.  When importing from a file, only a count of the rows is returned (which is reasonable).  Here we add in an ability to find the data items that were inserted or updated during an upload operation by way of a new audit event type, which is created when the transaction begins and contains a unique transactionId that can then be stored in other audit logs as a reference.  
* [Issue 39594](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39594)
This also adds a …

Item 7882: Add support for discovery of data involved in transactions through detailed audit logging

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/domainproperties/dataset/DatasetDesignerPanels.tsx

Issue [41574](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41574): Mapping visit field to a demographics dataset is required when inferring a field from a file
* https://github.com/LabKey/platform/pull/1640
* DatasetDesignerPanels update to check for demographic dataset configuration when validating column mapping

Issue 41574: Dataset designer file import column mapping fix for demographics dataset creation case

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/models.ts
packages/components/src/public/QueryModel/ChartMenu.tsx
packages/components/src/public/QueryModel/ViewMenu.tsx

GridPanel does not honor the hideEmptyChartSelector or hideEmptyViewSelector settings.
* https://github.com/LabKey/sampleManagement/pull/385
* https://github.com/LabKey/inventory/pull/112
* Issue 41068: GridPanel does not respect the hideEmptyChartSelector and hideEmptyViewSelector properties set in a
global query metadata override
* Renamed global settings 'hideEmptyViewSelector', 'hideEmptyChartSelector' to 'hideEmptyViewMenu', 'hideEmptyChartMenu'

Issue 41068

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/base/models/User.ts
packages/components/src/internal/components/notifications/__snapshots__/Notification.spec.tsx.snap

Make it so the type of `User` and `UserWithPermissions` are compatible.
* https://github.com/LabKey/biologics/pull/718
* Switch `IUserProps` to fully extend `UserWithPermissions`.

User is UserWithPermissions

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/index.ts
packages/components/src/internal/components/base/Permissions.spec.tsx
packages/components/src/internal/components/base/Permissions.tsx
packages/components/src/internal/components/base/ServerContext.tsx
packages/components/src/internal/testHelpers.ts
packages/components/src/internal/util/helpLinks.tsx

This PR does three things:
1. Hoists the implementation for `<RequiresPermissionHOC/>` into a shared component now called `<RequiresPermission/>`
1. Hoists `ServerContext` and it's associated providers/hooks from Biologics so it can be shared across apps. This is now leveraged by `<RequiresPermission/>` to source the `User`.
1. Removes `<PermissionAllowed/>` and `<PermissionNotAllowed/>` as they are no longer utilized.
* https://github.com/LabKey/biologics/pull/719
* https://github.com/LabKey/sampleManagement/pull/386
* https://github.com/LabKey/inventory/pull/113
* Add `RequiresPermission` (formerly known in apps as `RequiresPermissionHOC`).
* Add `ServerContext` to allow retrieving up-to-date server context via React.Context.
* Remove `<PermissionAllowed/>` and `<PermissionNotAllowed/>` …

RequiresPermission, ServerContext

---

packages/build/package.json
packages/build/webpack/README.md
packages/build/webpack/constants.js
packages/components/releaseNotes/labkey/build.md

The initial v0.1.0 of @labkey/build was fixed on using a relative path to get to the labkey-ui-components repository when using "npm run start-link". This version update changes that to using a LABKEY_UI_COMPONENTS_HOME environment variable so that each dev can set it based on their local setup.
* https://github.com/LabKey/labkey-ui-components/pull/379
* https://github.com/LabKey/platform/pull/1664
* https://github.com/LabKey/inventory/pull/117
* https://github.com/LabKey/provenance/pull/42
* https://github.com/LabKey/moduleEditor/pull/17
* https://github.com/LabKey/commonAssays/pull/252
* https://github.com/LabKey/tutorialModules/pull/30
* Use a LABKEY_UI_COMPONENTS_HOME environment variable from the user's setup to define the path for the webpack aliasing of @labkey packages when using …

@labkey/build update to use a LABKEY_UI_COMPONENTS_HOME environment variable for webpack aliasing of @labkey packages

---

packages/build/package.json
packages/build/webpack/constants.js
packages/components/releaseNotes/labkey/build.md

Gradle build caching requires that the directories designated as output directories be fully under the control of the build, so any task that outputs files to a directory that may already be occupied by checked-in files makes a task not able to be cached.  With the next version of gradlePlugin, we'll have tasks enabled for using the build cache.
* https://github.com/LabKey/gradlePlugin/pull/98
* https://github.com/LabKey/platform/pull/1662
* Generate files into``views/gen` instead of `views` for better cleaning and caching possibilities

Generate files into views/gen instead of views for better cleaning and caching possibilities

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/base/CreatedModified.spec.tsx
packages/components/src/internal/components/base/CreatedModified.tsx
packages/components/src/internal/components/files/FilesListing.tsx
packages/components/src/internal/components/files/FilesListingForm.tsx
packages/components/src/internal/components/files/WebDav.ts
packages/components/src/internal/components/files/models.ts
packages/components/src/internal/components/forms/input/AliasInput.tsx
packages/components/src/internal/components/forms/renderers.tsx
packages/components/src/internal/components/listing/pages/QueryDetailPage.tsx
packages/components/src/internal/components/navigation/BreadcrumbCreate.spec.tsx
packages/components/src/internal/components/navigation/BreadcrumbCreate.tsx
packages/components/src/public/QueryModel/QueryModel.ts
packages/components/src/stories/FilesListingForm.tsx
packages/components/src/stories/PageDetailHeader.tsx

As we migrate our usages of `QueryGridModel` to `QueryModel` we'll also be updating our shared components to be more easily used with either implementation. This PR updates the following:
* `<CreatedModified/>` is switched from using taking a `Map<string, any>` to a `Record<string, any>`. This reduces our dependence on `ImmutableJS`. `QueryGridModel` usages can use `Map.toJS()` and pass to the associated `<CreatedModified/>`.
* `resolveDetailFieldValue` is used to resolve data from a variety of object types. This PR updates the types and streamlines the logic so it works with `Immutable` types as well as `Record`.
Additionally, this work has been done in tandem with the Experiment updates in Biologics. As a part of this work Biologics now utilizes the shared `FilesListingForm` as well as …

Component updates for use with QueryModel

---

packages/components/README.md
packages/components/docs/immer.md
packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/yarn.lock

We have completed the checklist of required items to get us to the first official stable release of the @labkey/components. This PR includes a few doc updates to support that release. Note that since there are no source code changes in this PR, I am not planning on creating specific PRs for platform, biologics, sampleManagement, etc. to pull in this version. They will just pick it up when they are ready.
* doc updates to support bumping @labkey/components version to v1.0.0
* remove gh-pages from devDependencies

Update to first official stable release of @labkey/components v1.0.0

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/domainproperties/ConfirmImportTypes.tsx
packages/components/src/internal/components/domainproperties/dataset/DatasetDesignerPanels.tsx
packages/components/src/internal/components/domainproperties/list/ListDesignerPanels.tsx
packages/components/src/internal/components/report-list/__snapshots__/ReportList.spec.tsx.snap

An error arises when a field's type is inferred, but past the number of values used to infer that type, there is a value that conflicts with the already-inferred type. The changes allow the user to return to their domain and make manual edits to the field types.
* https://github.com/LabKey/platform/pull/1697
* Creates a confirmation modal
* Stores domain prior to save, to revert back to
* Drops created domain
* Applies to List and Dataset

Issue41460: Type conflict on infer fields 

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/domainproperties/ConfirmImportTypes.tsx

> The title mentions "dataset" (correct) but the message itself refers to "list" twice (incorrect). Message should always reference the appropriate table type ("dataset" in this case).
* https://github.com/LabKey/platform/pull/1722
* Use domain type in dialogue

41854: Wording updates for domain designer error dialog 

---

packages/components/src/internal/components/buttons/ActionButton.spec.tsx
packages/components/src/internal/components/buttons/ActionButton.tsx
packages/components/src/internal/components/buttons/AddEntityButton.spec.tsx
packages/components/src/internal/components/buttons/__snapshots__/ActionButton.spec.tsx.snap
packages/components/src/internal/components/buttons/__snapshots__/AddEntityButton.spec.tsx.snap
packages/components/src/internal/components/domainproperties/DomainForm.spec.tsx
packages/components/src/internal/components/domainproperties/actions.spec.ts
packages/components/src/stories/DomainForm.tsx

Adds Jest tests for added functionality
* https://github.com/LabKey/labkey-ui-components/pull/378
* https://github.com/LabKey/platform/pull/1661
* https://github.com/LabKey/sampleManagement/pull/391
* Added tests for functions processJsonImport, downloadJsonFile
* Exercise allowImportExport Prop in DomainForm
* Update tests for refactored ActionButton and AddEntityButton components
* Fix minor type issue in ActionButton

7984: Field Editor Import & Export Unit Tests

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/app/scss/variables.scss

Some variables used in the exported scss variables were not being defined, causing applications that want to use these variables to have to define them separately.  We also need some more gray variables.  Can never have too many gray variables.
* https://github.com/LabKey/inventory/pull/133
* Define missing variables
* Export a couple of other variables.

Define and export more scss variables

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/forms/PageDetailHeader.tsx
packages/components/src/internal/components/forms/__snapshots__/PageDetailHeader.spec.tsx.snap
packages/components/src/internal/components/user/__snapshots__/UserDetailHeader.spec.tsx.snap
packages/components/src/internal/query/api.ts
packages/components/src/stories/PageDetailHeader.tsx
packages/components/src/theme/detail.scss

For LKSM and LKFM they use the insertRows, updateRows, and deleteRows helpers from the @labkey/components package when making API calls for storage actions. The updateRows and deleteRows success response objects were not consistent with the insertRows response. This PR makes them consistent (most notably adding the "rows" to the deleteRows response).
* https://github.com/LabKey/sampleManagement/pull/414
* https://github.com/LabKey/inventory/pull/139
* https://github.com/LabKey/labkey-ui-components/pull/399
* make sure to include "rows" and "transactionAuditId" for updateRows and deleteRows wrapper functions
* minor display / layout fix for PageDetailHeader body content to flow better below image

Item 8116: Make insertRows, updateRows, and deleteRows API success response consistent

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/components/auditlog/TimelineView.tsx
packages/components/src/internal/components/auditlog/__snapshots__/TimelineView.spec.tsx.snap
packages/components/src/internal/components/forms/detail/DetailEditing.tsx
packages/components/src/public/QueryInfo.ts
packages/components/src/theme/fields.scss
packages/components/src/theme/timeline.scss

During testing for LKFM, we discovered a few areas where long display names for users can cause the page flow to behave in unfortunate ways.  We correct this by hiding the text using CSS styling.
* 
* Disable "Submit" button on DetailEditing when in the process of submitting
* Add some styling to hide text that overflows a field

Item 8117: Hide overly long display values and disable Submit button for DetailEditing when submitting

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/app/utils.spec.ts
packages/components/src/internal/app/utils.ts
packages/components/src/internal/components/auditlog/utils.spec.ts

Freezer management is no longer an experiment; it's a reality.  We're moving on to developing asynchronous import, which will need its own experimental flag and will likely affect some of the components in here.
* https://github.com/LabKey/inventory/pull/147
* https://github.com/LabKey/sampleManagement/pull/425
* Remove reference to the freezer management experimental flag
* Add method for checking for asynchronous import experimental flag

Remove experimental flag for freezer management within LKSM

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/index.ts
packages/components/src/internal/actions.ts

dataRegionSelectionKey holds a data region's checked row keys in session, which has been used by LKSM and LKFM to retrieve the set of samples or workflows to operate on. When there are user filters applied on the data region the client side (QueryGridModel or QueryModel), the set of selections may contain those that would have been filtered out on the active view. The desired behavior is for LKSM and LKFM actions to operate on filtered selections only.
Without affecting the existing selection handling, this PR adds a new setSnapshotSelections action to allow storing filtered selection using a new session key
* https://github.com/LabKey/platform/pull/1747
* https://github.com/LabKey/labkey-ui-components/pull/401
* https://github.com/LabKey/inventory/pull/145
* …

Issue 41737: Storage actions do not respect filters on the grid

---

packages/components/releaseNotes/labkey/themes.md
packages/themes/package.json
packages/themes/styles/scss/labkey/_labkey.scss

[Issue 41972](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41972) describes how some UI indicators in the pipeline job details page are no longer appearing properly. This was a regression that occurred when porting the themes into their own package (see #347). This PR uncomments the `font-family` and `content` declarations related to `pre.labkey-log-text` so that these indicators appear as expected.
* https://github.com/LabKey/platform/pull/1750
* Uncomment `font-family` and `content` declarations as it was an unintended change.

@labkey/themes - 41972: Fix expand indicators

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/util/RouteLeave.tsx

[Issue #41419](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41419)
* TBD SM
* TBD Inventory
* Update RouteLeave.confirmLeaveWhenDirty
Browser's back button still has bad state. Per Issue discussion may need to bump react-router version to fix.
Update release notes

Dirty form transition confirmation doesn't update history correctly

---

packages/components/package.json
packages/components/releaseNotes/labkey/components.md
packages/components/src/internal/app/index.ts
packages/components/src/internal/components/entities/EntityInsertPanel.tsx
packages/components/src/internal/components/files/FileAttachmentContainer.tsx
packages/components/src/internal/components/files/FileAttachmentForm.tsx
packages/components/src/internal/query/api.ts
packages/components/yarn.lock

EntityInsertPanel is used to handle import of samples and sources. Currently, it rejects any file that's larger than the configured 5mb. With async import support added, EntityInsertPanel should be able to accept larger files and determine actions to take based on file size. 
* https://github.com/LabKey/platform/pull/1770
* https://github.com/LabKey/labkey-api-js/pull/81
* https://github.com/LabKey/labkey-ui-components/pull/410
* https://github.com/LabKey/sampleManagement/pull/427
* add allowAsync for EntityInsertPanel

Item 6775: Asynchronous import for samples and sources

---

packages/build/package-lock.json
packages/build/package.json
packages/build/releaseNotes/build.md
packages/build/webpack/constants.js

Nick discovered that the hot module reload for various LK modules was broken because of the change in the related PR for the @labkey/build package to replace the postcss.config.js file with inline properties in the webpack config. I had missed adding the necessary props to the `STYLE_LOADERS_DEV`. After further review, we were getting the same "postcss-loader is not being used" message in the prod build, so I removed that dev dependency with this PR. I believe it isn't being use anymore every since we converted the @labkey/components package to expose the SCSS files instead of having it build a css file.
* https://github.com/LabKey/labkey-ui-components/pull/428
* Remove postcss-loader from devDependencies and webpack/constants.js

@labkey/build - remove postcss-loader

---

packages/build/package.json
packages/build/releaseNotes/build.md
packages/build/webpack/README.md
packages/build/webpack/constants.js

Recent update to HtmlWebpackPlugin template in @labkey/build exposed an issue where the generated files are not case sensitive on all OSes.  Linux based OSes generate all lower case tags (e.g. `<permissionclasses>`).  This adds minify options to ensure case sensitivity.  A few other properties added to minify options as well.
* Add minify options to all HtmlWebpackPlugin configs

Add minify options to HtmlWebpackPlugin in @labkey/build

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/app/index.ts
packages/components/src/internal/app/utils.ts

Issue [42216](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=42216): SM: With two different browsers (one FireFox one Chrome) logging out in one browser will show a "You have been logged out" dialog in the other browser
* https://github.com/LabKey/labkey-ui-components/pull/434
* https://github.com/LabKey/inventory/pull/176
* https://github.com/LabKey/sampleManagement/pull/464
* https://github.com/LabKey/biologics/pull/775
* https://github.com/LabKey/platform/pull/1927
* add check for evt.wasClean in server event listener callbacks before dispatching (to match platform dom/WebSocket.js)

Issue 42216: Fix for logout event notification issue with different user sessions (i.e. different browsers)

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/components/base/Grid.spec.tsx
packages/components/src/internal/components/base/Grid.tsx
packages/components/src/internal/components/base/__snapshots__/Grid.spec.tsx.snap

Zero is a fine value, so we should display it if we get it.
* change from truthy check to comparison to `undefined`.

Fix default grid cell rendered so it displays values that are 0.

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/components/domainproperties/DomainForm.tsx
packages/components/src/internal/components/domainproperties/DomainPropertiesGrid.spec.tsx
packages/components/src/internal/components/domainproperties/models.tsx

Catch two tweaks/bugs from manual testing of Summary View feature.
* https://github.com/LabKey/platform/pull/2026
* https://github.com/LabKey/sampleManagement/pull/494
* Makes auto-scroll feature in Summary View 'name' column expand corresponding field in detail mode
* Populates 'Range URI' column in Summary View for new fields

8049: Summary View Manual Testing Tweaks

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/index.ts
packages/components/src/public/QueryModel/GridPanel.tsx
packages/components/src/public/QueryModel/QueryModel.ts
packages/components/src/public/QueryModel/TabbedGridPanel.spec.tsx
packages/components/src/public/QueryModel/TabbedGridPanel.tsx
packages/components/src/theme/grid.scss

This PR adds a new component TabbedGridPanel, which can be used to replace old usages of QueryGridPanel that used the tabbed mode by passing multiple QueryGridModels. This component is however pretty different from QueryGridPanel's tabbed use case:
- QGP would by default hide empty tabs, TabbedGridPanel does not do this. This feature only worked properly if you also waited for all of your models to load before rendering the QGP so it wouldn't accidentally render an empty grid in the case that your first tab was empty. TabbedGridPanel expects consumers to filter out the tabs they want to hide.
- QGP would let you disable tab rendering via `showTabs`, this was only used to hide tabs in the rare case that we were using QGP in tabbed mode, but only passing it a single model to render. …

TabbedGridPanel

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/components/navigation/NavigationBar.tsx
packages/components/src/internal/components/navigation/__snapshots__/NavigationBar.spec.tsx.snap

This PR introduces two new flags, `showNotifications` and `showProductNav` to the `<NavigationBar/>` component props. These give our apps more fine-grain control over what is being displayed. Both default to `true`. This is targeted for `release21.3` as part of a fix for issue [#42589](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=42589).
* https://github.com/LabKey/biologics/pull/807
* Add and respect `showNotifications` and `showProductNav` props to `<NavigationBar />`.

NavigationBar: showNotifications, showProductNav flags

---

packages/components/src/internal/components/domainproperties/NameAndLinkingOptions.spec.tsx
packages/components/src/internal/components/domainproperties/__snapshots__/NameAndLinkingOptions.spec.tsx.snap
packages/components/src/internal/components/files/FileTree.spec.tsx
packages/components/src/internal/components/files/FileTree.tsx

Jest test additions related to recent ontology related components changes.
* https://github.com/LabKey/labkey-ui-components/pull/439
* https://github.com/LabKey/labkey-ui-components/pull/452
* Jest test for NameAndLinkingOptions component usage of OntologyConceptAnnotation
* Jest test for FileTree NodeIcon and Header sub-components

Jest tests for Ontology related changes to NameAndLinkingOptions and FileTree components

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/index.ts
packages/components/src/internal/components/domainproperties/dataclasses/__snapshots__/DataClassDesigner.spec.tsx.snap
packages/components/src/internal/components/forms/QueryFormInputs.tsx
packages/components/src/internal/components/forms/QuerySelect.tsx
packages/components/src/internal/components/forms/actions.ts
packages/components/src/internal/components/forms/detail/Detail.spec.tsx
packages/components/src/internal/components/forms/detail/Detail.tsx
packages/components/src/internal/components/forms/detail/DetailDisplay.tsx
packages/components/src/internal/components/forms/detail/DetailEditRenderer.tsx
packages/components/src/internal/components/forms/detail/DetailEditing.spec.tsx
packages/components/src/internal/components/forms/detail/DetailEditing.tsx
packages/components/src/internal/components/forms/input/CheckboxInput.tsx
packages/components/src/internal/components/forms/input/SelectInput.tsx
packages/components/src/internal/components/forms/input/TextAreaInput.tsx
packages/components/src/internal/components/forms/renderers.tsx
packages/components/src/internal/components/listing/pages/QueryDetailPage.tsx
packages/components/src/internal/renderers.tsx
packages/components/src/internal/renderers/DefaultRenderer.tsx
packages/components/src/public/QueryModel/DetailPanel.tsx
packages/components/src/public/QueryModel/EditableDetailPanel.tsx

[Issue 42310](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=42310) indicates users having performance problems with detail pages when lookups are backed by large result sets. This PR addresses this by making `useQuerySelect` an option for use in detail edit rendering. The reason `QuerySelect` is useful is that it is built to handle larger result sets and allow the user to search through those results dynamically without having to front-load all the underlying data.
Something to note here is that `QueryFormInputs` already uses a `QuerySelect`. The configuration of the input components is very similar between `resolveDetailEditRenderer` and `QueryFormInputs` - so much so that I've put in a note to indicate these should likely be merged into one implementation in …

Support QuerySelect in Detail Editing

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/components/editable/EditableGrid.tsx

This PR addresses [Issue 42608](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=42608) to fix the inadvertent copy of invalid keys in bulk edited data. See the ticket for detailed more information.
* https://github.com/LabKey/biologics/pull/814
* https://github.com/LabKey/sampleManagement/pull/505
* Remove both `numItems` and `creationType` metadata keys from the bulk data before continuing processing.
* Lint.

42608: Bulk Insert erroneously transposes columns

---

packages/build/package.json
packages/build/releaseNotes/build.md
packages/build/webpack/lib.template.xml

Minor fix to allow `generateLib: true` to work in app entryPoints.
* https://github.com/LabKey/platform/pull/2063
* Apply same parsing logic to `lib.template.xml` as was applied to `app.view.template.xml` in https://github.com/LabKey/labkey-ui-components/pull/461.

@labkey/build: fix file path parsing in lib.template.xml

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/actions.ts
packages/components/src/internal/components/QueryGrid.tsx
packages/components/src/internal/components/entities/EntityDeleteModal.tsx
packages/components/src/internal/components/entities/ParentEntityEditPanel.tsx
packages/components/src/internal/components/entities/SingleParentEntityPanel.spec.tsx
packages/components/src/internal/components/entities/SingleParentEntityPanel.tsx
packages/components/src/internal/components/entities/__snapshots__/ParentEntityEditPanel.spec.tsx.snap
packages/components/src/internal/components/entities/__snapshots__/SingleParentEntityPanel.spec.tsx.snap
packages/components/src/internal/components/entities/constants.ts
packages/components/src/internal/components/entities/utils.ts

The current `<SingleParentEntityPanel/>` (SPEP) is backed by `QueryGridModel` and it's associated components. All instances of SPEP's are created via `<ParentEntityEditPanel/>` and is responsible for their configuration. Formerly, this meant the parent would attempt to invalidate the underlying QGMs when either rows were updated or the parent component was unmounted. 
In a product test suite we're seeing failures due to this invalidation because it causes a race condition with grid initialization updates from the underlying `<QueryGrid/>`s created by the SPEPs. Due to the decoupled nature of these updates it is very difficult to catch/prevent this race condition.
With this PR I've updated `<SingleParentEntityPanel/>` to be backed by `QueryModel` and it's associated components. This …

QueryModel-based SingleParentEntityPanel

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/util/utils.ts

When the data passed in to `getDisambiguatedSelectInputOptions` is an object instead of an immutable map, we need to properly handle the case that one or more of the keys may be undefined or not available.
* https://github.com/LabKey/sampleManagement/pull/519
* https://github.com/LabKey/biologics/pull/830
* Fix problem with undefined references in `getDisambiguatedSelectInputOptions`

Issue 42635: Fix problem with undefined references in getDisambiguatedSelectInputOptions

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/public/QueryModel/QueryModel.spec.ts
packages/components/src/public/QueryModel/QueryModel.ts

We are currently showing the "Some selected" state when all rows are selected in a grid that has less than a page of data.
* https://github.com/LabKey/sampleManagement/pull/525
* update `selectedState` method and add tests

Fix selectedState for QueryModel when the total number of rows is less than the page size

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/index.ts
packages/components/src/internal/global.ts

QueryColumn lookup is fetched on first access and then stored in global state. For the scenario of adding samples to storage using editable grid, the lookup should be re-queried after each add action to get rid of those that are recently added to storage. 
* https://github.com/LabKey/inventory/pull/209
* 
* added lookupStoreInvalidate util

Issue 42383: FM: When adding samples to storage, the Sample ID dropdown in the editable grid often has a sampleId that is already in storage

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/internal/components/assay/AssayImportSubMenuItem.tsx
packages/components/src/internal/components/assay/actions.ts

This PR updates AssayImportSubMenuItem to have an optional `queryModel` prop so it can be used with QueryModel backed components. I needed this for a Biologics PR that is getting deferred indefinitely (upgrade Experiments Tabbed Grid Panel to use QueryModel). This will be useful in other areas of Biologics, as well as SM.
* n/a
* Add queryModel prop to AssayImportSubMenuItem
* Add getImportItemsForAssayDefinitionsQM to internal/components/assay/actions

Add queryModel prop to AssayImportSubMenuItem

---

packages/components/package.json
packages/components/releaseNotes/components.md
packages/components/src/index.ts
packages/components/src/internal/components/assay/AssayImportSubMenuItem.tsx
packages/components/src/internal/components/entities/EntityInsertPanel.tsx
packages/components/src/internal/components/entities/actions.spec.ts
packages/components/src/internal/components/entities/actions.ts
packages/components/src/internal/components/entities/constants.ts
packages/components/src/internal/components/entities/models.spec.ts
packages/components/src/internal/components/entities/models.ts
packages/components/src/internal/components/entities/utils.spec.ts
packages/components/src/internal/components/entities/utils.ts
packages/components/src/internal/components/menus/SubMenuItem.tsx

The related app PRs address a few LKSM and LKB issues for 21.4 related to sample creation scenarios. This PR makes a couple of related changes in the EntityInsertPanel component and models to handle these cases.
* https://github.com/LabKey/sampleManagement/pull/527
* https://github.com/LabKey/biologics/pull/840
* https://github.com/LabKey/labkey-ui-components/pull/483
* https://github.com/LabKey/testAutomation/pull/681
* EntityInsertPanel initParents handling of parent key without value to still add the parent type but not any default rows to the grid
* EntityDataType update to add editTypeAppUrlPrefix to fix links for editing type design
* EntityParentType update to add isParentTypeOnly for case mentioned above without parent key value

Misc SM and workflow fixes for 21.4
